version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # EXPOSE it to the internal Docker network
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis
    networks:
      - financial-network

  # nginx reverse-proxy
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - financial-network

  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - financial-network

  redis:
    image: redis:6
    volumes:
      - redis-data:/data
    networks:
      - financial-network

volumes:
  postgres-data:
  redis-data:

networks:
  financial-network:
    driver: bridge
