version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:22.14.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:kqGNwnee9s5lAOeMow5A/h57OtJsG5QlWNWZrixCek0"
      - run:
          name: Deploy to Kamatera
          command: |
            ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 ${SSH_USER}@${SSH_HOST} \<< 'EOF'
              cd ~/root/app
              git pull origin master
             docker compose -f docker-compose.yml down -v --remove-orphans
             docker network prune -f  # clean up unused networks
             docker compose -f docker-compose.yml build --no-cache
             docker compose -f docker-compose.yml up -d --scale app=3
            EOF

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
