version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:22.14.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:kqGNwnee9s5lAOeMow5A/h57OtJsG5QlWNWZrixCek0"
      - run:
          name: Deploy to Kamatera
          command: |
              ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 ${SSH_USER}@${SSH_HOST} \<< 'EOF'
                cd ~/app
                git pull origin master
                
                # Stop and remove all containers for this project
                docker compose -f docker-compose.yml down -v
                
                # Clean up any remaining containers (only if they exist)
                if [ "$(docker ps -aq)" ]; then
                  docker stop $(docker ps -aq)
                  docker rm $(docker ps -aq)
                fi
                
                # Clean up unused networks and volumes
                docker network prune -f
                
                # Build and start the application
                docker compose -f docker-compose.yml build
                docker compose -f docker-compose.yml up -d --scale app=3
              EOF

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master